services:
  flask-app:
    build: .
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=5000
    env_file:
      - .env
    expose:
      - "5000"
    volumes:
      - .:/app
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask-app
    networks:
      - app_network

  # Certbot service for renewals
  certbot:
    image: certbot/dns-cloudflare
    profiles: ["renewal"]
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./cloudflare.ini:/opt/certbot/cloudflare.ini
    command: >
      renew 
      --dns-cloudflare 
      --dns-cloudflare-credentials /opt/certbot/cloudflare.ini

networks:
  app_network:
    driver: bridge